# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: products-deployment
serviceName: products
appLabel: products
appName: products

replicaCount: 1

image:
  repository: ansgohar/product-catalogue-ms
  tag: v2.0

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false