spring:
  application:
    name: "configserver"
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
         native:
#           search-locations: "classpath:/config"
           search-locations: "file:////Users//ahmadgohar//Documents//config"
#        git:
#          uri: "https://github.com/ansgohar/commerce-config.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true

server:
  port: 8071
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

#encrypt:
#  key: "45D81EC1EF61DF9AD8D3E5BB397F9"



logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"